name: faizolanordin
favicon: null
layout_spectrum: 0.05140576767735183
typography_spectrum: 0.2736981362104416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.27777152182534337
  lightness: 0.7857328557875007
  saturation: 0.5540884826332331
  rhythmicContrast: 0.8708181537222117
purpose: []
